# Generated by Django 2.2 on 2020-08-16 07:21

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Change Leader', 'Change Leader'), ('Removal', 'Removal of a student from group'), ('Add', 'Addition of a student to a group')], max_length=36, verbose_name='action')),
                ('description', models.TextField(verbose_name='description')),
                ('generated', models.DateTimeField(auto_now=True, verbose_name='generated on')),
                ('processed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='processed on')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=10, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=40, verbose_name='status')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('description', models.TextField(verbose_name='description')),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last modified')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.RemoveField(
            model_name='team',
            name='approval',
        ),
        migrations.AddField(
            model_name='file',
            name='submitted_by',
            field=models.EmailField(default=1, max_length=254, verbose_name='submitted by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='turned_in',
            field=models.BooleanField(default=False, verbose_name='turned in'),
        ),
        migrations.AddField(
            model_name='guide',
            name='branch',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science'), ('Mech', 'Mechanical'), ('EXTC', 'Electronics And Telecommunication'), ('ETRX', 'Electronics')], default='IT', max_length=4, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=50, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Team', verbose_name='Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='team',
            name='guide',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Guide', verbose_name='guide'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='guide',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Guide', verbose_name='guide'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='marks_obtained',
            field=models.IntegerField(blank=True, null=True, verbose_name='marks obtained'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='thrust_area',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='new_leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.Student', verbose_name='new leader'),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='old_leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Student', verbose_name='old leader'),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Team', verbose_name='team'),
        ),
    ]
