# Generated by Django 2.2 on 2020-08-09 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200809_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Project', verbose_name='project'),
        ),
    ]
