# Generated by Django 2.2 on 2020-08-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Project', verbose_name='project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team', verbose_name='team'),
        ),
    ]
