# Generated by Django 2.2 on 2020-08-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Project', verbose_name='project'),
        ),
    ]
