# Generated by Django 2.2 on 2020-08-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200816_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprequest',
            name='add_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Student', verbose_name='add student'),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='remove_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Student', verbose_name='remove student'),
        ),
    ]
