# Generated by Django 2.2 on 2020-08-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200816_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprequest',
            name='add_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Student', verbose_name='add student'),
        ),
        migrations.AlterField(
            model_name='grouprequest',
            name='remove_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Student', verbose_name='remove student'),
        ),
    ]
