# Generated by Django 2.2 on 2020-08-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200816_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='branch',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science'), ('Mech', 'Mechanical'), ('EXTC', 'Electronics And Telecommunication'), ('ETRX', 'Electronics')], default='IT', max_length=40, verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='team',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Guide', verbose_name='guide'),
        ),
    ]
