# Generated by Django 2.2 on 2020-08-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200816_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Team', verbose_name='team'),
        ),
    ]
