# Generated by Django 2.2 on 2020-08-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_file_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_interest', models.CharField(choices=[('CS', 'Cyber Security (Forensics, Blockchain Technology, Biometrics Security, Cryptographic Techniques)'), ('IP', 'Image Processing (Computer Vision)'), ('AI', 'Artifical Intelligence (Machine Learning, Natural Language Processing, Robotics)'), ('CN', 'Computer Networking'), ('BD', 'Big Data Processing'), ('EHIA', 'Embedded and Hardware Integrated Applications (IOT)'), ('ARVR', 'Augmented Reality and Virtual Reality'), ('GIS', 'GIS'), ('CLOUD', 'Cloud Computing (High Performance Computing)'), ('SP', 'System Programming (Compiler construction, OS, Device drivers)'), ('QC', 'Quantum Computing'), ('STA', 'Software Testing Automation'), ('OTHER', 'Other')], max_length=256, verbose_name='area of interest')),
                ('thrust_area', models.CharField(choices=[('NS', 'Network and Security'), ('AD', 'Application Development'), ('IM', 'Information Management'), ('KS', 'Knowledge-based systems')], max_length=2, verbose_name='thrust area')),
            ],
        ),
        migrations.RemoveField(
            model_name='guide',
            name='area_of_interest',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='thrust_area',
        ),
        migrations.AddField(
            model_name='guide',
            name='preferences',
            field=models.ManyToManyField(to='api.Preference', verbose_name='preferences'),
        ),
    ]
