# Generated by Django 2.2 on 2020-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200817_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='preferences',
            field=models.ManyToManyField(blank=True, null=True, to='api.Preference', verbose_name='preferences'),
        ),
    ]
